### ISSUE TITLE
Revamp Pin on App UI

### ISSUE THREAD

**Issue by e-kibet** [joelkanyi/Savings-Zetu-App#30]
Have single TextView with the looping mechanism

**Comment by JoelKanyi** [comment]
Hello @e-kibet , thank you from your previous contributions. What part of the UI should have a single TextView.

**Comment by e-kibet** [comment]
Under res/layout/fragment_pay.xml instead of duplicates on the  1, 2, 3, 4 input. we can have a single textview and pass the values and ids on the payFragment section.

**Comment by JoelKanyi** [comment]
@e-kibet you can go ahead make that change

**Comment by e-kibet** [comment]
Ok @JoelKanyi thank you. Please assign me the task
